token:
  expiration_time: 86400000 # 24 hours
  secret: '{cipher}AYAj7qcOa3nA/ZYi57PcnA299U9QRolRXs5njfcEI6N4TY6mXr1banQntfEO1Qa7jzC299PEcH4vQlQfA/r8t3XJcZcNtkFgDH5xtCV7y0D/FWlO5XyaXMbDDA56dKq471BOdJYE2Mbxey8t/PH4dj6/N7Ux140bwcNvi74Uj/0D3yb2GGaSz6XiqRFBnWQP10j+1/s0/JeplfqWBj5SAz64M3XsgaLbpi3cEzoqMLV1g5Ovb7abA7Vic/a+Omuj82tPcacGZBd1fmAWT5hkH6PtkbXJzKEUD79sAKPbwAb4r1UuWFg5HtRLrQLl/dhzHQaFqYuV4PWLLzw3bFGLR8XxZ8YZfUUEYQ3gPO+Irju2PuL6tyo3L4kmJUzEvrHpPHuaRNX3fBY8OOnk0T/I5DdCreANRRtvZ0HewsuaxdPyW4IsLIyAa0Tv5b7DC+iktA6/MY+fZMNRKm7u2Getgm4RWUI8/PvBO5e348SSD7Farfrf9wkI78cX3JQV/M0qVv0f8gMl5YN2Dyrn3V6oAaNhzDpOMZra52DFOGiUJY9+ViiBmIb2OfPlZB4PKqY2GPH/w+ry74X7U50X/u8nPxVYJUHKxgjHsVdCMl9HqFYc1RuK2zyTfsb3XUNFhtKigs/wyAUfH2qcwh++P2f2kutnN4NoMVePzaG3e68Z3o7uALbsb7FAj9Dk/BfKQUTH2TY='

gateway:
  ip: 192.168.249.240

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AYBKgI9R2wAwOcmEWGubjQRjTLnWsazA2OymKy1SbTMf03iwdlgWmbnW38f3RW+28DOTWKq/axV8VP3ImmzqOtbyDjj0VL2dLI5uUPTq73yKWgJLPjLtOekfOdT6MvqG/z1NUJHNJngsBc0EgjUCqLDu+XYp2Mdrrx0VV/L+AmWIgQDyBGZDDUgj+/uwvaLTRlDo9JnpgQ97WnjbqCxePXMQ40na2I24SHhR5eEXrD0LPbPhwGUcnEJfTmkQoTfiMeIJDCpwzwiw12CUEuceyOKtAhOEi9qKTKu0FWRWHMlkvbZM+Pjjows6YqufYbZaNa2KfiXiYvMqUQFTZWkURt4QYw4q3E3A3OC5sM4DD2G+BVaPycvYRTKXOi/mRWDcTTYHrG1mRIi76FFRhq4E173lfAA7QFz74fAGVb/2luDM+I0jLtJx91W0VPR6WO4I8umCtPnqC/NDhJGQTDS3qdRGXo+HKKn6JlZI19KObq6B0BwACHdAXzht00Yy5g0747cXMGI1GsK5PnJRz2pR541n75s+Uvfcs1kTMzY+Yxf4rA=='

order_service:
  url: http://order-service/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is not found.
